### ISSUE TITLE
Major Error in UCP

### ISSUE THREAD

**Issue by phxinternational** [PGreca/pgsocial#49]
I am using phpbb 3.2.7 and when I go to UCP - ( Board Preferences/Edit Notification Options ) I get the following errors below

Fatal error: Uncaught ArgumentCountError: Too few arguments to function pgreca\pgsocial\notification\social_tag::__construct(), 7 passed in /var/www/vhosts/domain.com/httpdocs/cache/production/container_4335734bbdd20f586549a504dff5f80c.php on line 3045 and exactly 12 expected in /var/www/vhosts/domain.com/httpdocs/ext/pgreca/pgsocial/notification/social_tag.php:46 Stack trace: #0 /var/www/vhosts/domain.com/httpdocs/cache/production/container_4335734bbdd20f586549a504dff5f80c.php(3045): pgreca\pgsocial\notification\social_tag->__construct(Object(phpbb\db\driver\factory), Object(phpbb\language\language), Object(phpbb\user), Object(phpbb\auth\auth), './', 'php', 'cbx_user_notif...') #1 /var/www/vhosts/domain.com/httpdocs/vendor/symfony/dependency-injection/Container.php(295): phpbb_cache_container->getPgreca_Pgsocial_Notification_Type_SocialTagService() #2 /var/www/vhosts/domain.com/httpdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(446): Symfony\Component\DependencyInjection\Container->get in /var/www/vhosts/domain.com/httpdocs/ext/pgreca/pgsocial/notification/social_tag.php on line 46

**Comment by Mightymax44** [comment]
hi
Open config/services.yml and change code with the older code lines 127=> 131 pgreca\pgsocial\notification\social_tag and lines 136 =>140 class: pgreca\pgsocial\notification\social_zebra.
https://github.com/PGreca/pgsocial/commit/d40eb0c4bec3806f30d77f65bfcb864f5e2c408b
and purge the cache of your board and it's ok

**Comment by phxinternational** [comment]
Hi mate, I'm not sure what you mean? change code with the older code? That link you just posted is that the fixed file? Because that is the file that is already in my directory.

**Comment by phxinternational** [comment]
I got it ... yes it does work. Thanks for that!

**Comment by Mightymax44** [comment]
@phxinternational 
dowload this file https://mega.nz/file/tMYk0CRD#oRzlBzs8iGnhb_8zpd5ZOWv40wrPtWf5_vV1g1_mkqg and replace your files in /ext/config

**Comment by phxinternational** [comment]
@Mightymax44  Got it working, Thanks mate. Lets hope he does a bit more work on this extension soon. Not been any activity for a month.

**Comment by Mightymax44** [comment]
@phxinternational  
I update my fork with the latest fixes and add the deletion of chat messages when I updated my fork if you wish, I warn you. I think pgreca is busy.
